/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pmtToFile.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ae919aa13ad92a40c9b2a1bc37702208)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <adsbTestBlocks/pmtToFile.h>
// pydoc.h is automatically generated in the build directory
#include <pmtToFile_pydoc.h>

void bind_pmtToFile(py::module& m)
{

    using pmtToFile    = gr::adsbTestBlocks::pmtToFile;


    py::class_<pmtToFile, gr::block, gr::basic_block,
        std::shared_ptr<pmtToFile>>(m, "pmtToFile", D(pmtToFile))

        .def(py::init(&pmtToFile::make),
           py::arg("filename"),
           py::arg("test"),
           D(pmtToFile,make)
        )
        



        ;




}








