/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pointVec.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9d97c2e084a1cfedc6bf861972ac0bbb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <adsbTestBlocks/pointVec.h>
// pydoc.h is automatically generated in the build directory
#include <pointVec_pydoc.h>

void bind_pointVec(py::module& m)
{

    using pointVec    = gr::adsbTestBlocks::pointVec;


    py::class_<pointVec, gr::block, gr::basic_block,
        std::shared_ptr<pointVec>>(m, "pointVec", D(pointVec))

        .def(py::init(&pointVec::make),
           D(pointVec,make)
        )
        



        ;




}








